### ISSUE TITLE
POSIX memory check for Linux should use 'available'

### ISSUE THREAD

**Issue by briskt** [NodePing/PUSH_Clients#28]
I have been using the memory push check on Linux and have found it very useful. Then I started noticing what appeared to be a memory leak. What I found was that the check reports "free" memory which doesn't consider cache memory that is available for use, unlike "available". Depending on the application, both might be of interest. 

I modified the script locally to use available in addition to free. I am not familiar with BSD memory terminology, so I don't know how this compares in that environment. Should I submit this edit as a PR so someone else can add to the BSD part of it?

``` Shell
free -m | awk 'NR==2{printf "{\"free\":%s,\"available\":%s}", $4, $7 }'
```

**Comment by NodePing** [comment]
There is a difference between free and available memory and varies from system to system in how available memory is interpreted. Currently, the Python client has modules for both free and available. It would be confusing to make the memory module that is intended to report back free memory change to and handle available memory. 

`free` is a Linux-specific in part because it uses `/proc/meminfo` to parse the data, which procfs has been deprecated from the BSDs. Since `free` is Linux-only and changing behavior would confuse those who expect it to report free, I will add an "available memory" module that will handle the results you are looking for.
