### ISSUE TITLE
Diskfree report is a decimal that doesn't reflect free disk space

### ISSUE THREAD

**Issue by bserem** [NodePing/PUSH_Clients#37]
Diskfree metric reports a decimal number for every mount point (linux) that is a bit cryptic.

Examples:
```
"diskfree": {
  "/": 0.3,
  "/boot": 0.75
}

$ df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg0-root  186G  130G   48G  74% /
/dev/vda1             232M   58M  159M  27% /boot
```

```
diskfree": {
  "/": 0.28,
  "/boot": 0.32,
  "/boot/efi": 0.99,
  "/home": 0.89,
  "/home/bserem/STORAGE": 0.72
}

$ df -h
Filesystem                  Size  Used Avail Use% Mounted on
/dev/mapper/dwarf--vg-root   28G   20G  6,2G  77% /
/dev/sda2                   237M  162M   63M  73% /boot
/dev/sda1                   511M  5,3M  506M   2% /boot/efi
/dev/mapper/dwarf--vg-home  415G   48G  346G  13% /home
/dev/sdb1                   458G  128G  307G  30% /home/bserem/STORAGE
```

I can't see how 74% usage matches with `0.3` or how 13% matches `0.89` are results being rounded up/down?

Thanks!

**Comment by NodePing** [comment]
diskfree reports back how much disk space you have free on a scale of 0.0 to 1.0. So 0.28 would be 28% of your disk is free. You could think of the 0.3 being 0.30, or 30%. May I ask which filesystem(s) you're using? At least with ext4 creation, and perhaps even ext2/3, they have a 5% reserve set aside for the super user (man page for `mk2fs` -m flag for reference). This would make sense with the 0.3 report of diskfree and the 74% use, which would create roughly a 1% variation with that 5% reserve considered. The tool rounds down, where it's possible that `df` rounds up. `df` does not account for that 5% reserve, where diskfree will since it is looking at all the blocks on a partition.

You might be able to see the percentages more clearly and how far off they are in `df` by running it by itself or `df -BM` to at least get it in what looks like Mebibytes.

If the reporting of diskfree doesn't fit the use case you want, you may be interested in the disk_utilization metric with the POSIX client which will report the % of disk space used in whole number format, not the amount of disk space that is free.

Hopefully that helps

**Comment by bserem** [comment]
Excellent reply! I was expecting the round up/down but I did not account the filesystem reserves.

I took the liberty to update the docs for POSIX and Python3 (and a small change in the readme so it gets displayed better).

Hope you like it
